//! `havn setup` — one-shot wizard that creates the config file and data
//! directories so the gateway can come up cleanly on first run.
//!
//! Idempotent: an existing config is left untouched (the user must explicitly
//! delete it to rewrite). Data directories are created as missing.

use std::io::{IsTerminal as _, Write as _};
use std::path::{Path, PathBuf};

use anyhow::{Context as _, anyhow};

const DEFAULT_LISTEN: &str = "127.0.0.1:8080";
const DEFAULT_HEARTBEAT_MIN: u32 = 30;

#[derive(Debug, Clone)]
pub struct Plan {
    pub config_path: PathBuf,
    pub data_dir: PathBuf,
    pub listen: String,
    pub heartbeat_minutes: u32,
}

impl Plan {
    pub fn defaults() -> anyhow::Result<Self> {
        let home = home_dir()?;
        Ok(Self {
            config_path: home.join(".config/havn/config.toml"),
            data_dir: home.join(".local/share/havn"),
            listen: DEFAULT_LISTEN.into(),
            heartbeat_minutes: DEFAULT_HEARTBEAT_MIN,
        })
    }

    pub fn render_config(&self) -> String {
        let db = self.data_dir.join("havn.db");
        let socket = self.data_dir.join("agent.sock");
        let agents_root = self.data_dir.join("agents");
        format!(
            r#"# havn gateway config (generated by `havn setup`).
# Spec §12.1.

listen = {listen:?}
db_path = {db:?}
agent_socket_path = {socket:?}
workspace_root = {agents_root:?}

# WebChat Origin allowlist (spec §11 ClawJacked-class mitigation).
allowed_origins = ["http://localhost:3000", "http://127.0.0.1:3000"]

[reload]
# v0.6 default: restart on config change. Easy to reason about, no
# surprise live-mutation bugs. Switch to "hybrid" if you want in-process
# hot reload for dev iteration; see spec §8.4.
mode = "restart"
debounce_ms = 300

[trust_header]
# Spec §1.7: havn does no auth. Single-user loopback installs leave
# this `false` — the bootstrap user owns everything. To run multi-user,
# put a reverse proxy in front (Authelia, Keycloak, Cloudflare Access,
# Tailscale, nginx auth_request, …) that emits X-User-ID, set this to
# `true`, change `listen` above to a non-loopback address, and
# pre-provision users with `havn user add <id> --display-name "..."`.
#
# The gateway refuses to start with a non-loopback listen address
# unless this flag is true (or `HAVN_TRUST_HEADER=1` is set).
enabled = false

[defaults]
model = "claude-opus-4-6"
memory_mb = 512
cpu_cores = 1.0
heartbeat_minutes = {hb}
"#,
            listen = self.listen,
            db = db.display().to_string(),
            socket = socket.display().to_string(),
            agents_root = agents_root.display().to_string(),
            hb = self.heartbeat_minutes,
        )
    }
}

/// Run the setup wizard. When `interactive` is false, no prompts are shown
/// — defaults are accepted automatically. CI / smoke tests pass `false`.
pub fn run(interactive: bool) -> anyhow::Result<()> {
    let mut plan = Plan::defaults()?;
    if interactive && std::io::stdin().is_terminal() {
        plan = prompt_for_plan(plan)?;
    }
    apply(&plan)?;
    report_kernel_capabilities();
    Ok(())
}

/// Setup-time host-kernel capability report (spec §16). Today this is
/// just the nested user-namespace check — relevant to any capability
/// pack whose workload nests user namespaces (e.g. browser packs
/// running Chromium with its own sandbox). Informational only:
/// failure does NOT abort `havn setup`. Operators who don't intend to
/// install such a pack can ignore the warning.
fn report_kernel_capabilities() {
    println!();
    println!("kernel capability report (spec §16):");
    #[cfg(target_os = "linux")]
    {
        let result = crate::nested_ns::check();
        let (short, long) = result.explain();
        match result {
            crate::nested_ns::NestedUserNsResult::Ok => {
                println!("  ✓ {short}");
            }
            _ => {
                println!("  ⚠ {short}");
                if let Some(remediation) = long {
                    println!();
                    for ln in remediation.lines() {
                        println!("    {ln}");
                    }
                }
            }
        }
    }
    #[cfg(not(target_os = "linux"))]
    {
        println!("  ⚠ non-Linux host — havn agent isolation requires Linux user namespaces");
    }
}

fn apply(plan: &Plan) -> anyhow::Result<()> {
    if let Some(parent) = plan.config_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    if plan.config_path.exists() {
        println!(
            "config already exists at {} — leaving untouched",
            plan.config_path.display()
        );
    } else {
        std::fs::write(&plan.config_path, plan.render_config())
            .with_context(|| format!("writing {}", plan.config_path.display()))?;
        println!("✓ wrote {}", plan.config_path.display());
    }

    std::fs::create_dir_all(&plan.data_dir)
        .with_context(|| format!("creating {}", plan.data_dir.display()))?;
    std::fs::create_dir_all(plan.data_dir.join("agents"))?;
    println!("✓ data dir {}", plan.data_dir.display());

    println!();
    println!("next:");
    println!("  havn start                        # launch the gateway");
    println!(
        "  havn credential add anthropic <KEY>  # add an LLM provider key (after gateway is up)"
    );
    println!("  havn agent create my-agent        # create your first agent");
    Ok(())
}

fn prompt_for_plan(mut plan: Plan) -> anyhow::Result<Plan> {
    let listen = ask("Gateway listen address", &plan.listen)?;
    let config = ask("Config path", &plan.config_path.display().to_string())?;
    let data = ask("Data directory", &plan.data_dir.display().to_string())?;

    plan.listen = listen;
    plan.config_path = PathBuf::from(config);
    plan.data_dir = PathBuf::from(data);
    Ok(plan)
}

fn ask(label: &str, default: &str) -> anyhow::Result<String> {
    print!("{label} [{default}]: ");
    std::io::stdout().flush().ok();
    let mut buf = String::new();
    std::io::stdin().read_line(&mut buf)?;
    let trimmed = buf.trim();
    Ok(if trimmed.is_empty() {
        default.into()
    } else {
        trimmed.into()
    })
}

fn home_dir() -> anyhow::Result<PathBuf> {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .ok_or_else(|| anyhow!("HOME not set"))
}

#[allow(dead_code, reason = "exposed for upcoming `havn doctor` health-check")]
pub fn config_exists(path: &Path) -> bool {
    path.exists()
}

#[cfg(test)]
mod tests {
    #![allow(clippy::expect_used, clippy::unwrap_used)]

    use super::*;

    fn tempdir() -> PathBuf {
        let mut p = std::env::temp_dir();
        p.push(format!("havn-cli-setup-{}", uuid_like()));
        std::fs::create_dir_all(&p).unwrap();
        p
    }

    fn uuid_like() -> u128 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0)
    }

    #[test]
    fn render_config_contains_required_keys() {
        let plan = Plan {
            config_path: PathBuf::from("/tmp/havn/config.toml"),
            data_dir: PathBuf::from("/tmp/havn"),
            listen: "127.0.0.1:8080".into(),
            heartbeat_minutes: 30,
        };
        let rendered = plan.render_config();
        for key in &[
            "listen",
            "db_path",
            "agent_socket_path",
            "workspace_root",
            "allowed_origins",
            "[reload]",
            "[defaults]",
            "heartbeat_minutes",
        ] {
            assert!(rendered.contains(key), "config missing {key}");
        }
        // Loopback default per spec §11.
        assert!(rendered.contains("127.0.0.1:8080"));
    }

    #[test]
    fn apply_writes_config_and_creates_dirs() {
        let dir = tempdir();
        let plan = Plan {
            config_path: dir.join("config.toml"),
            data_dir: dir.join("data"),
            listen: "127.0.0.1:8080".into(),
            heartbeat_minutes: 30,
        };
        apply(&plan).expect("apply");
        assert!(plan.config_path.exists());
        assert!(plan.data_dir.exists());
        assert!(plan.data_dir.join("agents").exists());
    }

    #[test]
    fn apply_is_idempotent() {
        let dir = tempdir();
        let plan = Plan {
            config_path: dir.join("config.toml"),
            data_dir: dir.join("data"),
            listen: "127.0.0.1:8080".into(),
            heartbeat_minutes: 30,
        };
        apply(&plan).unwrap();
        // Mutate the config — second apply should not overwrite.
        std::fs::write(&plan.config_path, "user-edited").unwrap();
        apply(&plan).unwrap();
        let after = std::fs::read_to_string(&plan.config_path).unwrap();
        assert_eq!(after, "user-edited");
    }
}
